# Name of the snippet:
TARGET_NAME = program

# Specify all source files:
SOURCES = main.c

# Specify all include paths:
INCLUDES = -I.
INCLUDES += -I../utils

# Specify defines:
DEFINES =
#DEFINES += ...

include ../global.mk
