# Name of the snippet:
TARGET_NAME = program

# Specify all source files:
SOURCES = main.c
SOURCES += ../utils/grid2d.c
SOURCES += ../utils/queue.c

# Specify all include paths:
INCLUDES = -I.
INCLUDES += -I../utils

# Specify defines:
DEFINES =
#DEFINES += ...

include ../global.mk
